Added copyright, missing diffs and extra logs

diff --git a/hooks/config-changed b/hooks/config-changed
--- a/hooks/config-changed
+++ b/hooks/config-changed
@@ -20,9 +20,10 @@ mgmtinterface=$(config-get n1kv-vsm-mgmt-interface)
 mgmtmac=$(config-get n1kv-vsm-mgmt-mac)
 pktinterface=$(config-get n1kv-vsm-pkt-interface)
 pktmac=$(config-get n1kv-vsm-pkt-mac)
+vcpu=$(config-get n1kv-vsm-vm-vcpu)
+disksize=$(config-get n1kv-vsm-disk-size)
 VERSION=$(config-get n1kv-version)
 LOCAL_REPO=$(config-get n1kv-local-repo)
-
 
 finaliso=${VSM_VM_DIR}/${vsmrole}_repacked.iso
 diskfile=${VSM_VM_DIR}/${vsmrole}_disk
@@ -87,16 +88,38 @@ function repack_iso
 {
     juju-log "Repack the VSM ISO with the setup script environment variables"
     pwd
+    if [ "${vsmrole}" == "secondary" ]; then
+        mgmtip="0.0.0.0"
+        mgmtnetmask="0.0.0.0"
+        mgmtgateway="0.0.0.0"
+    fi
+    if [ $adminpasswd == "" ]; then
+        print "Error: invalid vsm admin password"
+        return 1
+    fi
+    if [ $mgmtip == "" ]; then
+        print "Error: invalid mgmt ip"
+        return 1
+    fi
+    if [ $mgmtnetmask == "" ]; then
+        print "Error: invalid mgmt netmask"
+        return 1
+    fi
+    if [ $mgmtgateway == "" ]; then
+        print "Error: invalid mgmt gateway"
+        return 1
+    fi
     ./hooks/lib/repackiso.py -i ${VSM_ISO} -d $domainid -n ${VSM_NAME} -m $mgmtip -s $mgmtnetmask -g $mgmtgateway -p $adminpasswd -r $vsmrole -f $finaliso
+    return 0
 }
 
 #Generate the vsm vm xml file
 function generate_vsm_vm_xml
 {
     juju-log "Compile the vsm_vsm.xml from the template"
-    cheetah fill --env --oext compiled templates/vsm_vm.xml.tmpl
-    cp templates/vsm_vm.xml.compiled /var/spool/vsm/vsm_vm.xml
-    juju-log "vsm_vm.xml creation done" 
+    cheetah fill --env --oext compiled templates/${VSM_VM_XML}.tmpl
+    cp templates/${VSM_VM_XML}.compiled ${VSM_VM_DIR}/${VSM_VM_XML}
+    juju-log "${VSM_VM_XML} creation done" 
 }
 
 function add_remote_repo
@@ -208,9 +231,14 @@ if [ $? -eq 0 ]; then
     fi
     start_openvswitch
     update_ovs_interfaces
-    created=`/usr/bin/virsh list --all | grep -c ' ${VSM_NAME}'`
+    created=`/usr/bin/virsh list --all | grep -c ${VSM_NAME}`
     if [ $created -eq 0 ]; then
+        juju-log "Going to repackage and create vsm vm"
         repack_iso
+        if [ $? -eq 1 ]; then
+            juju-log "Error: couldn't repackage vsm iso"
+            exit 1
+        fi
         generate_vsm_vm_xml
         qemu_img_create
     fi
